version: '3'

volumes:
  rabbitmq_data:
    driver: local
  portainer_data:

services:
  node-s:
    build:
        context: ./node-s
    container_name: nodejss
    hostname: nodejss
    ports:
       - "8080:8080"
    networks:
      - net-example

  angular-s:
    build:
      context: ./angular-s
    container_name: angulars
    hostname: angulars
    ports:
      - "4200:4200"
    networks:
      - net-example
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
       - "80:80"
    networks:
      - net-example
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.8
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
    - '4369:4369'
    - '5672:5672'
    - '25672:25672'
    - '15672:15672'
    environment:
    - RABBITMQ_USERNAME=andre
    - RABBITMQ_PASSWORD=andre
    - RABBITMQ_SECURE_PASSWORD=yes
    - RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT=1MB
    volumes:
    - 'rabbitmq_data:/bitnami'
    networks:
    - net-example
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    hostname: portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
    - net-example
  prometheus:
    hostname: prometheus
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    volumes:
     - ./etc/prometheus/:/etc/prometheus/
     - ./data/prometheus/:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
     - 9090:9090
    networks:
     - net-example
  grafana:
    hostname: grafana
    image: grafana/grafana
    container_name: grafana
    ports:
     - 3000:3000
    volumes:
      - ./data/grafana/:/var/lib/grafana
      - ./etc/grafana/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    networks:
     - net-example
networks:
  net-example:
    external: true